#!/bin/sh

if
	[ $GIT_AUTHOR_EMAIL != "pharaun666@gmail.com" ] ||
	[ $GIT_COMMITTER_EMAIL != "pharaun666@gmail.com" ] ||
	[ $EMAIL != "pharaun666@gmail.com" ]
then
	echo "Check your email address!"
	echo "GIT_AUTHOR_EMAIL: $GIT_AUTHOR_EMAIL"
	echo "GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL"
	echo "EMAIL: $EMAIL"
	exit 1
fi
